### ISSUE TITLE
xception backbone is incomplete ,and it not work

### ISSUE THREAD

**Issue by lbwnb-max** [armbrustsamuel/xception_mask_rcnn#1]

**Comment by armbrustsamuel** [comment]
Hi @soutnwind6, unfortunately, I was not able to finish it yet. I noticed that this R-CNN implementation does not support branch models, so that is why I stopped working on it. 

I intend to continue working on it in the next couple of months. If you have some suggestions on how to do it, please feel free to suggest. Thank you for your interest. Samuel
